### ISSUE TITLE
Establish how features are generated and how they will be used

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-features-api#5]
As product owners, we need to pin down the intended usage patterns of the features API, so we can define the features of the API.

## Acceptance criteria:
- [x] Talked to Alexey https://github.com/NASA-IMPACT/veda-features-api/issues/5#issuecomment-1248098367
- [x] Wrote tech specs for feature **consumption** (here or in https://drive.google.com/drive/folders/1E_bUjP8DoIhVBugnnsqoztuCIjbfgfH9)
- [ ] Wrote tech specs for feature **generation / ingestion** (here or in https://drive.google.com/drive/folders/1E_bUjP8DoIhVBugnnsqoztuCIjbfgfH9)

**Comment by j08lue** [comment]
Superseded by information gathered during EIS user support - more discovery needed in the future for Dashboard vector data interaction.
